import pandas as pd
import numpy as np
df = pd.read_csv('telecom_churn.csv')
df.head()
#print(df.shape)
#print(df.columns)
#print(df.info())
df['Churn'] = df['Churn'].astype('int64')
#print(df.describe(include=['object','bool']))
#print(df['Churn'].value_counts())
#print(df['Area code'].value_counts(normalize = True))
#print(df.sort_values(by = 'Total day charge', ascending = False).head())
#print(df.sort_values(by = ['Churn', 'Total day charge'], ascending=[True, False]).head())
#print(df['Churn'].mean())
#print(df[df['Churn']==1].mean())
#print(df[df['Churn']==1]['Total day minutes'].mean())
#print(df[(df['Churn']==0)&(df['International plan']=='No')]['Total intl minutes'].max())
#print(df.loc[0:5, 'State':'Area code'])
#print(df.iloc[0:5, 0:3])
#print(df[-1:])
#print(df.apply(np.max))
d = {'No':False, 'Yes':True}
df['International plan']=df['International plan'].map(d)
#print(df.head())
df = df.replace({'Voice mail plan':d})
#print(df.head())
Columns_to_show = ['Total day minutes', 'Total eve minutes', 'Total night minutes']
#print(df.groupby(['Churn'])[Columns_to_show].describe(percentiles=[]))
print(df.groupby(['Churn'])[Columns_to_show].agg([np.mean, np.std, np.max, np.min]))
